spring:
    application:
        name: inventory-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/inventory_service
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
    zipkin:
        base-url: http://localhost:9411
    sleuth:
      sampler:
          probability: 1.0
    cloud:
      compatibility-verifier:
          enabled: false
server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://eureka:password@localhost:8761/eureka

